config/routes.rb
NkuRails::Application.routes.draw do
  resources :attendances
  resources :sessions
  resources :students, except: :edit do
    resources :attendances
    resources :assignments
  end
  resources :assignments do
    collection { post :import }
  end

  get "sign_out", to: "sessions#destroy"
  get "profile", to: "students#edit"
  get "abcenses", to: "students#abcense"
  post "students/setDate", to: "students#setDate"
  root to: "students#index"
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :student
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :student
end

app/models/avatar.rb
class Avatar
  GRAVATAR_BASE_URL = "http://www.gravatar.com/avatar/"
  GRAVATAR_DEFAULT = "mm"
  SIZE = 200

  def self.from_student(student)
    new(image_url: student.image_url, email: student.email)
  end

  def initialize(attributes)
    @image_url = attributes[:image_url]
    @email = attributes[:email]
  end

  def to_s
    if @image_url.present?
      @image_url
    elsif @email.present?
      gravatar_url
    else
      fallback_url
    end
  end

  private

  def gravatar_url
    gravatar_from_digest Digest::MD5.hexdigest(@email)
  end

  def fallback_url
    gravatar_from_digest(123)
  end

  def gravatar_from_digest(digest)
    "#{GRAVATAR_BASE_URL}#{digest}?s=#{SIZE}&d=#{GRAVATAR_DEFAULT}"
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_secure_password
  has_many :attendances, dependent: :destroy

  def avatar
    Avatar.from_student(self)
  end
  
  def self.in_seat(seat, pick_date)
    return Student.find(Attendance.where(attendances: {seat: seat, attended_on: pick_date}).collect { |a| a.student_id})    
  end

  def self.absent(pick_date)
    return Student.where.not(id: Attendance.where(attendances: {attended_on: pick_date}).collect { |a| a.student_id})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
  def current_student
    @current_student ||= Student.find_by(id: session[:student_id]) if session[:student_id].present?
  end
  helper_method :current_student
  private
  
 def require_login
   unless current_student
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_student_path
    end
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def index
    @assignment = Assignment.all
    if params[:student_id].present?
      @assignment=Student.find(params[:student_id]).assignments
    else
      nil
    end
  end
  def destroy
    @assignment=Assignment.find(params[:id])
    @assignment.destroy
    redirect_to assignments_path, notice: "Assignment deleted"
  end
  def create
    @assignment = Assignment.new(assignment_params)
    if @assignment.save
      redirect_to assignments_path, notice: "Assigment created"
    else
      render 'new'
    end
  end
  def new
      @assignment = Assignment.new
  end
  def import
    Assignment.import(params[:file])
    redirect_to assignments_path, notice: "Uploaded"
  end
 private
    def assignment_params
      params.require(:assignment).permit(:student, :name, :score, :total)
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  def new 
    @attendance = Attendance.new
  end
  
  def create
    @attendance = Attendance.new
    @attendance.attended_on = Date.today
    @attendance.seat = params[:attendance][:seat]
    @attendance.student_id = current_student.id
    
    @attendance_exists = Attendance.where(attendances: {attended_on: Date.today, student_id: current_student.id})
    
    if(@attendance_exists.first == nil)
      @attendance.save
      redirect_to attendances_path, :notice => "You have successfully logged your attendance."
    else
      flash[:error] = "You have already created an attendance for today."
      render "new"
    end

  end
  
  def show
    @attendance = Attendance.find(params[:id])
  end
  
  def index
    @attendances = Attendance.all
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  def create
    student = Student.find_by(email: session_params[:email])
    if student && student.authenticate(session_params[:password])
      session[:student_id] = student.id
      redirect_to students_path, notice: "Signed in!"
    else
      flash[:error] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:student_id] = nil
    redirect_to root_path, notice: "Signed out!"
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def new
    @student = Student.new
  end

  def create
    @student = Student.create!(student_params)
    session[:student_id] = @student.id
    redirect_to students_path, notice: "Hi #{@student.name}. Welcome to Bueller!"
  end

  def edit
    @student = current_student
  end

  def update
    current_student.update_attributes!(student_params)
    redirect_to students_path, notice: "Successfully updated your profile"
  end
 
  def index
    @current_date = params[:date_var] || Date.today
    @students = Student.all
    @seat1 = Student.in_seat("1", @current_date)
    @seat2 = Student.in_seat("2", @current_date)
    @seat3 = Student.in_seat("3", @current_date)
    @seat4 = Student.in_seat("4", @current_date)
    @notHere = Student.absent(@current_date)
  end

  private

  def student_params
    params.require(:student).permit!
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-info"
    end
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/assignments/_form.html.erb
<div class="row col-sm-6">
  <%= form_for @assignment do |f| %>
    <div class="form-group">
      <%= f.label "Student" %>
      <%= collection_select(:student, :student_id, Student.all, :id, :name) %>
    </div>

    <div class="form-group">
      <%= f.label :name, 'Assignment Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :score, 'Score on Assignment' %>
      <%= f.text_field :score, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :total, 'Total Points Available' %>
      <%= f.text_field :total, class: 'form-control' %>
    </div>

    <%= f.submit %>
    &nbsp;or
    <%= link_to 'Cancel', assignments_path %>
  <% end %>
</div>

app/views/assignments/index.html.erb
<h1>Assignments</h1>
<% if current_student.try(:admin?) %>  
  <p>
    <label>Choose assignment to upload: </label>
      <%= form_tag import_assignments_path, multipart: true do %>
    <button class="bt btn-default navbar-btn"><%= file_field_tag :file%></button>
    <button class="bt btn-default navbar-btn">Import</button>    
    <% end %>
  <% end %>
</p>
<table>
  <tr>
    <td>Name</td>
    <td>Score</td>
    <td>total</td>
  </tr>
  <% total_of_totals = 0 %>
  <% total_of_scores = 0 %>
  <% @assignment.each do |a| %>
  <tr>
    <td><% a.name %></td>
    <td><% a.score %><% total_of_scores += total_of_scores %></td>
    <td><% a.total %><% total_of_totals += total_of_totals %></td>
  </tr>
  <tr>
    <td>Total of Scores</td>
    <td>Total of Totals</td>
    <td>Grade Percent</td>
  </tr>
  <tr>
    <td><% total_of_scores %></td>
    <td><% total_of_totals %></td>
    <td><% number_to_percentage(total_of_scores.to_f / total_of_totals * 100, precision: 0) %></td>
  </tr>
  <% end %>
</table>
  

app/views/assignments/new.html.erb
<h1>Add Assignment</h1>
<%= render partial: 'form' %>

app/views/attendances/index.html.erb
<h1>Attendances as of <%= Date.today %></h1>

<table cellpadding="15px">
  <tr>
    <td>Name</td>
    <td>Date</td>
    <td>Seat</td>
  </tr>
<% @attendances.each do |a| %>
  <tr>
    <td><%= link_to a.student.name, attendances_path %></td>
    <td><%= a.attended_on %></td>
    <td><%= a.seat %></td>
  </tr>
<% end %>

app/views/attendances/new.html.erb
<h1>Record your Attendance!</h1>
<%= form_for @attendance do |a| %>
<%= a.label :seat, "Enter Your Seat Number (1-4)" %>
<%= a.number_field :seat, min:1, max:4 %>
<%= a.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NkuRails</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <div class="navbar-brand">
        <%= link_to "Bueller", root_path %>
      </div>
    </div>

    <div class="collapse navbar-collapse navbar-right">
      <% if current_student.try(:admin?) %>
          <%= link_to "Upload an assignment", new_assignment_path, class: "btn btn-default navbar-btn" %>
          <%= link_to "View all assignments", assignments_path, class: "btn btn-default navbar-btn" %>
          <%= link_to "All Students", students_path %>
          <%= link_to "Attendances", attendances_path %>
          <%= link_to "Seating Chart", students_path %>
          <%= link_to "Absences", abcenses_path %>
          <%= link_to "My Assignments", assignments_path %>
      <% elsif current_student %> 
        <%= link_to "All Students", students_path %>
        <%= link_to "Attendances", attendances_path %>
        <%= link_to "Seating Chart", students_path %>
        <%= link_to "Absences", abcenses_path %>
        <%= link_to "My Assignments", assignments_path %>
      <% else %>
      <% end %>
      <% if current_student %>
        <p class="navbar-text current-student">
          Hi <%= current_student.name %>! <%= link_to "Edit your profile", profile_path %>
        </p>
        <%= link_to "I'm here!", new_attendance_path, class: "btn btn-default navbar-btn" %>
        <%= link_to "Sign out", sign_out_path, class: "btn btn-default navbar-btn"%> 
      <% else %>
        <%= link_to "Sign up", new_student_path, class: "btn btn-default navbar-btn" %>
        <%= link_to "Sign in", new_session_path, class: "btn btn-primary navbar-btn" %>
      <% end %>
    </div>
  </nav>

  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> push--top">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/students/_form.html.erb
<div class="row col-sm-6">
  <%= form_for @student do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :nickname, 'Nickname' %>
      <%= f.text_field :nickname, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :image_url, 'Image URL' %>
      <%= f.text_field :image_url, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Password' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, 'Password Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :admin, 'Admin?' %>
      <%= f.label :admin, "Yes", :value => "true" %>
      <%= f.radio_button :admin, true %>
      <%= f.label :admin, "No", :value => "false" %>
      <%= f.radio_button :admin, false, :checked => true %>
    </div>


    <%= f.submit submit_copy, class: 'btn btn-primary' %>
    &nbsp;or
    <%= link_to 'Cancel', students_path %>
  <% end %>
</div>

app/views/students/abcenses.html.erb
<h1>Who's Absent?</h1>
  <% @notHere.each do |n| %>
   <div class="avatar pull-left" style='background-image: url(<%= n.avatar %>)'></div>

    <div class="list-item">
      <h4><%= n.name %></h4>
      <p><em>(<%= n.nickname %>)</em></p>
      <p><%= n.email %></p>
     </div>
  <% end %>

app/views/students/edit.html.erb
<div class="page-header">
  <h1>Edit your profile</h1>
</div>

<%= render partial: 'form', locals: {submit_copy: 'Update profile'} %>

app/views/students/index.html.erb
<div class="page-header">
  <h1>Who's in class?</h1>
  <%= form_tag({:controller => "students"}, :method => :get) %> 
  <%= date_field_tag(:date_var, @current_date) %>
  <%= submit_tag %>
  <%= link_to "Attendances", attendances_path %>
</div>
<div style = "float:right, width:50%">
<table class="seating-table">
  <tbody>
  <tr>
  <td>
    <div style = "float:top"><h2>Seat 1</h2></div>
    <% @seat1.each do |s| %>
    <div class="avatar pull-left" style='background-image: url(<%= s.avatar %>)'></div>

    <div class="list-item">
      <h4><%= s.name %></h4>
      <h5><em>(<%= s.nickname %>)</em></h5>
      <h5><%= s.email %></h5>
     </div>
    <% end %>
   </td>
  <td>
    <div style = "float:top"><h2>Seat 2</h2></div>
    <% @seat2.each do |s| %>
    <div class="avatar pull-left" style='background-image: url(<%= s.avatar %>)'></div>

    <div class="list-item">
      <h4><%= s.name %></h4>
      <h5><em>(<%= s.nickname %>)</em></h5>
      <h5><%= s.email %></h5>
     </div>
    <% end %>
   </td>
 </tr>
 <tr>
  <td>
    <div style = "float:top"><h2>Seat 3</h2></div>
    <% @seat3.each do |s| %>
    <div class="avatar pull-left" style='background-image: url(<%= s.avatar %>)'></div>

    <div class="info-block">
      <h4><%= s.name %></h4>
      <h5><em>(<%= s.nickname %>)</em></h5>
      <h5><%= s.email %></h5>
     </div>
    <% end %>
   </td>
  <td>
    <div style = "float:top"><h2>Seat 4</h2></div>
    <% @seat4.each do |s| %>
    <div class="avatar pull-left" style='background-image: url(<%= s.avatar %>)'></div>

    <div class="info-block">
      <h4><%= s.name %></h4>
      <h5><em>(<%= s.nickname %>)</em></h5>
      <h5><%= s.email %></h5>
     </div>
    <% end %>
   </td>
  </tr>
  </tbody>
  <tfoot>
  <tr>
      <td colspan=2>Front of classroom</td>
    </tr>
  </tfoot>
</table>
</div>

app/views/students/new.html.erb
<div class="page-header">
  <h1>Sign Up for Bueller</h1>
</div>

<%= render partial: 'form', locals: {submit_copy: 'Sign up'} %>

app/views/students/show.html.erb
<h1>Students</h1>
<% @students.each do |student| %>
  <div id="<%=dom_id(student)%>" class="list-item">
    <div class="avatar pull-left" style='background-image: url(<%= student.avatar %>)'></div>

    <div class="info-block">
      <h4><%= student.name %></h4>
      <p><em>(<%= student.nickname %>)</em></p>
      <p><%= student.email %></p>
     </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails</h1>
<%= link_to "My Blog", controller: "posts" %>